In [1]:
# Import the dependencies.

import pandas as pd

import gmaps

import requests


# Import the API key.

from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.

city_data_df = pd.read_csv("weather_data/cities.csv")

city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Omboue,GA,2022-06-21 03:52:56,-1.5746,9.2618,70.20,90,63,9.31
1,1,Ushuaia,AR,2022-06-21 03:48:18,-54.8000,-68.3000,33.46,86,75,23.02
2,2,Varhaug,NO,2022-06-21 03:52:57,58.6147,5.6457,51.85,78,100,7.72
3,3,Ormara,PK,2022-06-21 03:52:57,25.2088,64.6357,90.12,48,1,11.61
4,4,Bhatkal,IN,2022-06-21 03:52:58,13.9667,74.5667,79.59,85,100,5.44

In [3]:
# Get the data types.

city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.

gmaps.configure(api_key=g_key)

In [5]:
# Heatmap of temperature.

locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.

max_temp = city_data_df["Max Temp"]

# Assign the figure variable.

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.

heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], 
                                 dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.

fig.add_layer(heat_layer)

# Call the figure to plat the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# Heatmap of humidity.

locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.

humidity = city_data_df["Humidity"]

# Assign the figure variable.

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.

fig.add_layer(heat_layer)

# Call the figure to plat the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of cloudiness.

locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.

clouds = city_data_df["Cloudiness"]

# Assign the figure variable.

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.

heat_layer = gmaps.heatmap_layer(locations, weights=clouds, 
                                 dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.

fig.add_layer(heat_layer)

# Call the figure to plat the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of wind speed.

locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.

wind = city_data_df["Wind Speed"]

# Assign the figure variable.

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.

heat_layer = gmaps.heatmap_layer(locations, weights=wind, 
                                 dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.

fig.add_layer(heat_layer)

# Call the figure to plat the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Ask the customer to add a minimum and maximum temperature value.

min_temp = float(input("What is the minimum temperature you would like for your trip? "))

max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 65
What is the maximum temperature you would like for your trip? 78

In [10]:
# Filter the dataset to find the cities that fit the criteria.

preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]

preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Omboue,GA,2022-06-21 03:52:56,-1.5746,9.2618,70.20,90,63,9.31
5,5,Damietta,EG,2022-06-21 03:52:58,31.4165,31.8133,75.09,70,0,6.55
11,11,Sao Felix Do Xingu,BR,2022-06-21 03:49:27,-6.6447,-51.9950,68.45,71,6,1.16
12,12,Puerto Ayacucho,VE,2022-06-21 03:53:01,5.6639,-67.6236,70.86,96,100,2.06
14,14,Charyshskoye,RU,2022-06-21 03:53:02,51.3978,83.5598,75.27,56,80,1.57
16,16,Quatre Cocos,MU,2022-06-21 03:53:03,-20.2078,57.7625,68.11,58,16,10.42
23,23,Gat,IL,2022-06-21 03:49:32,31.6100,34.7642,72.28,100,44,6.13
27,27,Dapaong,TG,2022-06-21 03:53:09,10.8639,0.2050,76.14,70,100,1.61
29,29,Mahebourg,MU,2022-06-21 03:53:10,-20.4081,57.7000,68.29,56,20,5.75
31,31,Vila Do Maio,CV,2022-06-21 03:53:11,15.1333,-23.2167,75.99,90,47,9.26

In [11]:
preferred_cities_df.count()

City_ID       219
City          219
Country       219
Date          219
Lat           219
Lng           219
Max Temp      219
Humidity      219
Cloudiness    219
Wind Speed    219
dtype: int64

In [12]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.

hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()

hotel_df["Hotel Name"] = ""

hotel_df.head(10)

                  City Country  Max Temp      Lat      Lng Hotel Name
0               Omboue      GA     70.20  -1.5746   9.2618
5             Damietta      EG     75.09  31.4165  31.8133
11  Sao Felix Do Xingu      BR     68.45  -6.6447 -51.9950
12     Puerto Ayacucho      VE     70.86   5.6639 -67.6236
14        Charyshskoye      RU     75.27  51.3978  83.5598
16        Quatre Cocos      MU     68.11 -20.2078  57.7625
23                 Gat      IL     72.28  31.6100  34.7642
27             Dapaong      TG     76.14  10.8639   0.2050
29           Mahebourg      MU     68.29 -20.4081  57.7000
31        Vila Do Maio      CV     75.99  15.1333 -23.2167

In [13]:
# Set parameters to search for a hotel.

params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [14]:
# Iterate through the DataFrame.

for index, row in hotel_df.iterrows():
    
    # Get the latitude and longitude.
    
    lat = row["Lat"]
    
    lng = row["Lng"]
    
    
    # Add the latitude and longitude to location key for the params dictionary.
    
    params["location"] = f"{lat},{lng}"
    
    
    # Use the searth term: "lodging" and our latitude and longitude.
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    
    try:
        
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [15]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Omboue,GA,70.20,-1.5746,9.2618,Hotel Olako
5,Damietta,EG,75.09,31.4165,31.8133,SULIMAN INN
11,Sao Felix Do Xingu,BR,68.45,-6.6447,-51.9950,Rio Xingu Camping
12,Puerto Ayacucho,VE,70.86,5.6639,-67.6236,Posada Turistica Manapiare
14,Charyshskoye,RU,75.27,51.3978,83.5598,Gostinitsa Charysh
16,Quatre Cocos,MU,68.11,-20.2078,57.7625,Sunrise Attitude Hotel
23,Gat,IL,72.28,31.6100,34.7642,OlusHome
27,Dapaong,TG,76.14,10.8639,0.2050,Hotel Caroli
29,Mahebourg,MU,68.29,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
31,Vila Do Maio,CV,75.99,15.1333,-23.2167,Hotel Marilu

In [16]:
# Add a heatmap of temperature for the vacation spots.

locations = hotel_df[["Lat", "Lng"]]

max_temp = hotel_df["Max Temp"]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, 
                                 dissipating=False, max_intensity=300, point_radius=4)

marker_layer = gmaps.marker_layer(locations)

fig.add_layer(heat_layer)

fig.add_layer(marker_layer)


# Call the figure to plat the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
info_box_template = """

<dl>

<dt>Hotel Name</dt><dd>{Hotel Name}</dd>

<dt>City</dt><dd>{City}</dd>

<dt>Country</dt><dd>{Country}</dd>

<dt>Max Temp</dt><dd>{Max Temp} °F</dd>

</dl>

"""

# Store the DataFrame Row.

hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [18]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.

locations = hotel_df[["Lat", "Lng"]]

max_temp = hotel_df["Max Temp"]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, 
                                 dissipating=False, max_intensity=300, point_radius=4)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(heat_layer)

fig.add_layer(marker_layer)


# Call the figure to plat the data.

fig

Figure(layout=FigureLayout(height='420px'))