## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

In [2]:
# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [5]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,East London,ZA,-33.0153,27.9116,58.03,50,0,7.45,clear sky
1,1,Ponta Do Sol,PT,32.6667,-17.1000,67.01,66,34,7.63,scattered clouds
2,2,Yar-Sale,RU,66.8333,70.8333,53.51,48,100,27.40,overcast clouds
3,3,Garowe,SO,8.4054,48.4845,76.91,57,41,31.88,scattered clouds
4,4,Roccastrada,IT,43.0099,11.1665,74.01,90,16,1.57,few clouds

In [6]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 

min_temp = float(input("What is the minimum temperature you would like for your trip? "))

max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 67
What is the maximum temperature you would like for your trip? 76

In [7]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]

preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Ponta Do Sol,PT,32.6667,-17.1000,67.01,66,34,7.63,scattered clouds
4,4,Roccastrada,IT,43.0099,11.1665,74.01,90,16,1.57,few clouds
17,17,Gambela,ET,8.2500,34.5833,71.19,84,100,5.75,light rain
18,18,Arnoldstein,AT,46.5461,13.7100,69.19,68,70,4.43,broken clouds
20,20,Horki,BY,54.2861,30.9842,67.98,90,8,6.15,clear sky
24,24,Ponta Delgada,PT,37.7333,-25.6667,67.50,68,75,5.75,broken clouds
32,32,Araxa,BR,-19.5933,-46.9406,67.96,56,40,2.30,scattered clouds
40,40,Maceio,BR,-9.6658,-35.7353,74.64,78,20,4.61,few clouds
41,41,Mahebourg,MU,-20.4081,57.7000,70.09,78,75,11.50,broken clouds
43,43,Hollola,FI,61.0500,25.4333,69.57,70,74,2.75,broken clouds

In [8]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                170
City                   170
Country                166
Lat                    170
Lng                    170
Max Temp               170
Humidity               170
Cloudiness             170
Wind Speed             170
Current Description    170
dtype: int64

In [15]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_clean_df = preferred_cities_df.dropna()
preferred_cities_clean_df.count()

City_ID                166
City                   166
Country                166
Lat                    166
Lng                    166
Max Temp               166
Humidity               166
Cloudiness             166
Wind Speed             166
Current Description    166
dtype: int64

In [21]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.tail(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
689,Tchibanga,GA,68.11,broken clouds,-2.8500,11.0333,
690,Big Rapids,US,68.32,clear sky,43.6981,-85.4837,
691,Makurdi,NG,73.65,overcast clouds,7.7411,8.5121,
692,Dennis,US,71.80,overcast clouds,41.7354,-70.1939,
695,Juba,SS,72.54,overcast clouds,4.8517,31.5825,
697,Tammisaari,FI,70.90,few clouds,59.9736,23.4339,
698,Trebinje,BA,71.96,clear sky,42.7119,18.3442,
699,Mamou,GN,71.38,broken clouds,10.5000,-12.0000,
705,Ilinskiy,RU,69.51,clear sky,55.6190,38.1182,
706,Moanda,GA,72.10,light rain,-1.5575,13.2178,

In [22]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame

    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
   
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [35]:
# 7. Drop the rows where there is no Hotel Name.

hotel_df["Hotel Name"].astype(bool)

hotel_clean_df = hotel_df[hotel_df["Hotel Name"].astype(bool)]

hotel_clean_df.count()

City                   140
Country                140
Max Temp               140
Current Description    140
Lat                    140
Lng                    140
Hotel Name             140
dtype: int64

In [37]:
# 8a. Create the output File (CSV)

output_data_file = "../Vacation_Search/WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
hotel_clean_df.to_csv(output_data_file, index_label="City_ID")

In [45]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

<dl>

<dt>Hotel Name</dt><dd>{Hotel Name}</dd>

<dt>City</dt><dd>{City}</dd>

<dt>Country</dt><dd>{Country}</dd>

<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>


</dl>

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_clean_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_clean_df[["Lat", "Lng"]]

In [46]:
# 11a. Add a marker layer for each city to the map. 

# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.

locations = hotel_clean_df[["Lat", "Lng"]]

max_temp = hotel_clean_df["Max Temp"]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, 
#                                 dissipating=False, max_intensity=300, point_radius=4)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# fig.add_layer(heat_layer)

fig.add_layer(marker_layer)


# 11b. Display the figure

fig

Figure(layout=FigureLayout(height='420px'))