## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,3,Garowe,SO,76.91,scattered clouds,8.4054,48.4845,Curubo Hotel
1,4,Roccastrada,IT,74.01,few clouds,43.0099,11.1665,La Melosa Resort & Spa
2,10,Acarau,BR,78.28,broken clouds,-2.8856,-40.1200,castelo pizzaria
3,16,Piney Green,US,80.55,overcast clouds,34.7160,-77.3202,Holiday City Mobile Home Community
4,27,Kutum,SD,81.43,broken clouds,14.2000,24.6667,Dibbo areaمنطقة دبو

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

<dl>

<dt>Hotel Name</dt><dd>{Hotel Name}</dd>

<dt>City</dt><dd>{City}</dd>

<dt>Country</dt><dd>{Country}</dd>

<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>


</dl>

"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
search_results = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.

locations = vacation_df[["Lat", "Lng"]]

max_temp = vacation_df["Max Temp"]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=search_results)

fig.add_layer(marker_layer)

# 4b. Display the figure

fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] == "Narasannapeta")]
vacation_end = vacation_df.loc[(vacation_df["City"] == "Narasannapeta")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == "Junagarh")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == "Malkangiri")] 
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == "Yanam")]

In [6]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.

import numpy as np
start = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
end = vacation_end["Lat"].to_numpy()[0], vacation_end["Lng"].to_numpy()[0]
stop1 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop1["Lng"].to_numpy()[0]
stop2 = vacation_stop2["Lat"].to_numpy()[0], vacation_stop2["Lng"].to_numpy()[0]
stop3 = vacation_stop3["Lat"].to_numpy()[0], vacation_stop3["Lng"].to_numpy()[0]

In [7]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

import gmaps.datasets

fig = gmaps.figure()
india_driving_layer = gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3], )
fig.add_layer(india_driving_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,351,Narasannapeta,IN,81.45,overcast clouds,18.4167,84.0500,AVK events and catering
1,46,Junagarh,IN,79.68,overcast clouds,19.8667,82.9333,Hotel Swagat
2,222,Malkangiri,IN,76.03,overcast clouds,18.3500,81.9000,MR-SAGAR_KUMAR_RTR™
3,491,Yanam,IN,79.07,overcast clouds,16.7333,82.2167,The Regency Hotel

In [9]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """

<dl>

<dt>Hotel Name</dt><dd>{Hotel Name}</dd>

<dt>City</dt><dd>{City}</dd>

<dt>Country</dt><dd>{Country}</dd>

<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>


</dl>

"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [10]:
# 11a. Add a marker layer for each city to the map.

locations = itinerary_df[["Lat", "Lng"]]

max_temp = itinerary_df["Max Temp"]

fig = gmaps.figure(center=(18.5, 84), zoom_level=7)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)



# 11b. Display the figure

fig

Figure(layout=FigureLayout(height='420px'))